############
# API INFO #
############

API_NAME = 'NexusML'
API_VERSION = 0

#############
# ENDPOINTS #
#############

SWAGGER_URL = '/swagger/'
SWAGGER_UI_URL = '/swagger-ui/'

SWAGGER_TAG_MYACCOUNT = 'My Account'
SWAGGER_TAG_ORGANIZATIONS = 'Organizations'
SWAGGER_TAG_TASKS = 'Tasks'
SWAGGER_TAG_SERVICES = 'Services'
SWAGGER_TAG_FILES = 'Files'
SWAGGER_TAG_AI = 'AI'
SWAGGER_TAG_EXAMPLES = 'Examples'
SWAGGER_TAG_TAGS = 'Tags'

# My Account
ENDPOINT_MYACCOUNT = '/myaccount'
ENDPOINT_MYACCOUNT_ORGANIZATION = ENDPOINT_MYACCOUNT + '/organization'
ENDPOINT_MYACCOUNT_ROLES = ENDPOINT_MYACCOUNT + '/roles'
ENDPOINT_MYACCOUNT_PERMISSIONS = ENDPOINT_MYACCOUNT + '/permissions'
ENDPOINT_MYACCOUNT_NOTIFICATIONS = ENDPOINT_MYACCOUNT + '/notifications'
ENDPOINT_MYACCOUNT_NOTIFICATION = ENDPOINT_MYACCOUNT_NOTIFICATIONS + '/<notification_id>'
ENDPOINT_MYACCOUNT_SETTINGS = ENDPOINT_MYACCOUNT + '/settings'
ENDPOINT_MYACCOUNT_CLIENTS_SETTINGS = ENDPOINT_MYACCOUNT_SETTINGS + '/apps'
ENDPOINT_MYACCOUNT_CLIENT_SETTINGS = ENDPOINT_MYACCOUNT_CLIENTS_SETTINGS + '/<client_id>'

# Organizations
ENDPOINT_ORGANIZATIONS = '/organizations'
ENDPOINT_ORGANIZATION = ENDPOINT_ORGANIZATIONS + '/<organization_id>'

ENDPOINT_SUBSCRIPTION = ENDPOINT_ORGANIZATION + '/subscription'

ENDPOINT_USERS = ENDPOINT_ORGANIZATION + '/users'
ENDPOINT_USER = ENDPOINT_USERS + '/<user_id>'
ENDPOINT_USER_ROLES = ENDPOINT_USER + '/roles'
ENDPOINT_USER_ROLE = ENDPOINT_USER_ROLES + '/<role_id>'
ENDPOINT_USER_PERMISSIONS = ENDPOINT_USER + '/permissions'
ENDPOINT_USER_INVITE = ENDPOINT_USERS + '/invite'

ENDPOINT_ROLES = ENDPOINT_ORGANIZATION + '/roles'
ENDPOINT_ROLE = ENDPOINT_ROLES + '/<role_id>'
ENDPOINT_ROLE_USERS = ENDPOINT_ROLE + '/users'
ENDPOINT_ROLE_PERMISSIONS = ENDPOINT_ROLE + '/permissions'

ENDPOINT_COLLABORATORS = ENDPOINT_ORGANIZATION + '/collaborators'
ENDPOINT_COLLABORATOR = ENDPOINT_COLLABORATORS + '/<collaborator_id>'
ENDPOINT_COLLABORATOR_PERMISSIONS = ENDPOINT_COLLABORATOR + '/permissions'

ENDPOINT_CLIENTS = ENDPOINT_ORGANIZATION + '/apps'
ENDPOINT_CLIENT = ENDPOINT_CLIENTS + '/<client_id>'
ENDPOINT_CLIENT_API_KEY = ENDPOINT_CLIENT + '/api-key'

# Organization Files
ENDPOINT_ORG_FILES = ENDPOINT_ORGANIZATION + '/files'
ENDPOINT_ORG_FILE = ENDPOINT_ORG_FILES + '/<file_id>'
ENDPOINT_ORG_FILE_PARTS = ENDPOINT_ORG_FILE + '/parts'
ENDPOINT_ORG_FILE_PARTS_COMPLETION = ENDPOINT_ORG_FILE_PARTS + '/complete'

# Tasks
ENDPOINT_TASKS = '/tasks'
ENDPOINT_TASK = ENDPOINT_TASKS + '/<task_id>'
ENDPOINT_TASK_SCHEMA = ENDPOINT_TASK + '/schema'
ENDPOINT_TASK_SETTINGS = ENDPOINT_TASK + '/settings'
ENDPOINT_TASK_STATUS = ENDPOINT_TASK + '/status'
ENDPOINT_TASK_QUOTA_USAGE = ENDPOINT_TASK + '/usage'

ENDPOINT_INPUT_ELEMENTS = ENDPOINT_TASK_SCHEMA + '/inputs'
ENDPOINT_INPUT_ELEMENT = ENDPOINT_INPUT_ELEMENTS + '/<input_id>'
ENDPOINT_OUTPUT_ELEMENTS = ENDPOINT_TASK_SCHEMA + '/outputs'
ENDPOINT_OUTPUT_ELEMENT = ENDPOINT_OUTPUT_ELEMENTS + '/<output_id>'
ENDPOINT_METADATA_ELEMENTS = ENDPOINT_TASK_SCHEMA + '/metadata'
ENDPOINT_METADATA_ELEMENT = ENDPOINT_METADATA_ELEMENTS + '/<metadata_id>'

ENDPOINT_INPUT_CATEGORIES = ENDPOINT_INPUT_ELEMENT + '/categories'
ENDPOINT_INPUT_CATEGORY = ENDPOINT_INPUT_CATEGORIES + '/<category_id>'
ENDPOINT_OUTPUT_CATEGORIES = ENDPOINT_OUTPUT_ELEMENT + '/categories'
ENDPOINT_OUTPUT_CATEGORY = ENDPOINT_OUTPUT_CATEGORIES + '/<category_id>'
ENDPOINT_METADATA_CATEGORIES = ENDPOINT_METADATA_ELEMENT + '/categories'
ENDPOINT_METADATA_CATEGORY = ENDPOINT_METADATA_CATEGORIES + '/<category_id>'

# Services
ENDPOINT_SERVICES = ENDPOINT_TASK + '/services'
ENDPOINT_SERVICES_API_KEYS = ENDPOINT_SERVICES + '/api-keys'

ENDPOINT_INFERENCE_SERVICE = ENDPOINT_SERVICES + '/inference'
ENDPOINT_CL_SERVICE = ENDPOINT_SERVICES + '/continual-learning'
ENDPOINT_AL_SERVICE = ENDPOINT_SERVICES + '/active-learning'
ENDPOINT_MONITORING_SERVICE = ENDPOINT_SERVICES + '/monitoring'
ENDPOINT_TESTING_SERVICE = ENDPOINT_SERVICES + '/testing'

ENDPOINT_INFERENCE_SERVICE_STATUS = ENDPOINT_INFERENCE_SERVICE + '/status'
ENDPOINT_CL_SERVICE_STATUS = ENDPOINT_CL_SERVICE + '/status'
ENDPOINT_AL_SERVICE_STATUS = ENDPOINT_AL_SERVICE + '/status'
ENDPOINT_MONITORING_SERVICE_STATUS = ENDPOINT_MONITORING_SERVICE + '/status'
ENDPOINT_TESTING_SERVICE_STATUS = ENDPOINT_TESTING_SERVICE + '/status'

ENDPOINT_INFERENCE_SERVICE_NOTIFICATIONS = ENDPOINT_INFERENCE_SERVICE + '/notifications'
ENDPOINT_CL_SERVICE_NOTIFICATIONS = ENDPOINT_CL_SERVICE + '/notifications'
ENDPOINT_AL_SERVICE_NOTIFICATIONS = ENDPOINT_AL_SERVICE + '/notifications'
ENDPOINT_MONITORING_SERVICE_NOTIFICATIONS = ENDPOINT_MONITORING_SERVICE + '/notifications'
ENDPOINT_TESTING_SERVICE_NOTIFICATIONS = ENDPOINT_TESTING_SERVICE + '/notifications'

ENDPOINT_MONITORING_SERVICE_TEMPLATES = ENDPOINT_MONITORING_SERVICE + '/templates'

# Task Files
ENDPOINT_TASK_FILES = ENDPOINT_TASK + '/files'
ENDPOINT_TASK_FILE = ENDPOINT_TASK_FILES + '/<file_id>'
ENDPOINT_TASK_FILE_PARTS = ENDPOINT_TASK_FILE + '/parts'
ENDPOINT_TASK_FILE_PARTS_COMPLETION = ENDPOINT_TASK_FILE_PARTS + '/complete'

# AI
ENDPOINT_AI_TRAINING = ENDPOINT_TASK + '/train'
ENDPOINT_AI_INFERENCE = ENDPOINT_TASK + '/predict'
ENDPOINT_AI_TESTING = ENDPOINT_TASK + '/test'
ENDPOINT_AI_MODELS = ENDPOINT_TASK + '/models'
ENDPOINT_AI_MODEL = ENDPOINT_AI_MODELS + '/<model_id>'
ENDPOINT_AI_DEPLOYMENT = ENDPOINT_TASK + '/deployment'
ENDPOINT_AI_PREDICTION_LOGS = ENDPOINT_TASK + '/prediction-logs'
ENDPOINT_AI_PREDICTION_LOG = ENDPOINT_AI_PREDICTION_LOGS + '/<prediction_id>'

# Examples
ENDPOINT_EXAMPLES = ENDPOINT_TASK + '/examples'
ENDPOINT_EXAMPLE = ENDPOINT_EXAMPLES + '/<example_id>'
ENDPOINT_EXAMPLE_COMMENTS = ENDPOINT_EXAMPLE + '/comments'
ENDPOINT_EXAMPLE_SHAPES = ENDPOINT_EXAMPLE + '/shapes'
ENDPOINT_EXAMPLE_SHAPE = ENDPOINT_EXAMPLE_SHAPES + '/<shape_id>'
ENDPOINT_EXAMPLE_SLICES = ENDPOINT_EXAMPLE + '/slices'
ENDPOINT_EXAMPLE_SLICE = ENDPOINT_EXAMPLE_SLICES + '/<slice_id>'

# Tags
ENDPOINT_TAGS = ENDPOINT_TASK + '/tags'
ENDPOINT_TAG = ENDPOINT_TAGS + '/<tag_id>'

# Local File Storage Backend
ENDPOINT_ORG_LOCAL_FILE_STORE = ENDPOINT_ORGANIZATION + '/file-store'
ENDPOINT_ORG_LOCAL_FILE_STORE_DOWNLOAD = ENDPOINT_ORG_LOCAL_FILE_STORE + '/download/<file_id>'
ENDPOINT_ORG_LOCAL_FILE_STORE_UPLOAD = ENDPOINT_ORG_LOCAL_FILE_STORE + '/upload/<file_id>'
ENDPOINT_ORG_LOCAL_FILE_STORE_MULTIPART_UPLOAD = ENDPOINT_ORG_LOCAL_FILE_STORE + '/multipart-uploads/<upload_id>'

ENDPOINT_TASK_LOCAL_FILE_STORE = ENDPOINT_TASK + '/file-store'
ENDPOINT_TASK_LOCAL_FILE_STORE_DOWNLOAD = ENDPOINT_TASK_LOCAL_FILE_STORE + '/download/<file_id>'
ENDPOINT_TASK_LOCAL_FILE_STORE_UPLOAD = ENDPOINT_TASK_LOCAL_FILE_STORE + '/upload/<file_id>'
ENDPOINT_TASK_LOCAL_FILE_STORE_MULTIPART_UPLOAD = ENDPOINT_TASK_LOCAL_FILE_STORE + '/multipart-uploads/<upload_id>'

##########
# ENGINE #
##########

# Set a maximum number of classes for not computing all metrics and the confusion matrix
# When dealing with too many classes, the computation of each value of the confusion matrix is too expensive
# So we set a threshold, and above this threshold we don't compute confusion matrix metrics and figure
ENGINE_MAX_NUM_CLASSES = 50

# Min overlap value to use for calculating metrics on object detection and object segmentation
# ODS -> Object Detection/Segmentation
ENGINE_ODS_MIN_OVERLAP = 0.5

# The classification models return the score for each class. Sometimes, there are too many classes for a response,
# so we have to limit them. This constant control the number of maximum classes score to return (as a default
# value, that can be modified as an argument of nexusml.engine.data.utils.predictions_to_example_format function)
ENGINE_LIMIT_SCORE_CLASSES = 50

# Because the model are too big to be uploaded in just one request, they are uploaded splitting them in several parts.
# This constant controls the size of each part
ENGINE_MODEL_CHUNK_SIZE = 100 * 1024 * 1024

##############
# FILE STORE #
##############

PREFIX_TASKS = 'tasks/'
PREFIX_TASK_MODELS = 'models/'
PREFIX_TASK_INPUTS = 'inputs/'
PREFIX_TASK_OUTPUTS = 'outputs/'
PREFIX_TASK_METADATA = 'metadata/'
PREFIX_TASK_PICTURES = 'pictures/'

PREFIX_ORGANIZATIONS = 'organizations/'
PREFIX_ORG_PICTURES = 'pictures/'

PREFIX_THUMBNAILS = 'thumbnails/'

MIN_FILE_PART_SIZE = 5 * 1024**2  # 5 MB

#########
# REDIS #
#########

REDIS_PREDICTION_LOG_BUFFER_KEY = 'nexusml_prediction_log_buffer'

##############################################################
# HTTP STATUS CODES                                          #
#                                                            #
# - https://datatracker.ietf.org/doc/html/rfc7231#section-6  #
# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status #
##############################################################

# Successful
HTTP_GET_STATUS_CODE = 200
HTTP_PUT_STATUS_CODE = 200
HTTP_POST_STATUS_CODE = 201
HTTP_DELETE_STATUS_CODE = 204

# Client Errors
HTTP_BAD_REQUEST_STATUS_CODE = 400
HTTP_UNAUTHORIZED_STATUS_CODE = 401
HTTP_FORBIDDEN_STATUS_CODE = 403
HTTP_NOT_FOUND_STATUS_CODE = 404
HTTP_METHOD_NOT_ALLOWED_STATUS_CODE = 405
HTTP_CONFLICT_STATUS_CODE = 409
HTTP_PAYLOAD_TOO_LARGE_STATUS_CODE = 413
HTTP_UNPROCESSABLE_ENTITY_STATUS_CODE = 422
HTTP_TOO_MANY_REQUESTS_STATUS_CODE = 429

# Server Errors
HTTP_NOT_IMPLEMENTED_STATUS_CODE = 501
HTTP_SERVICE_UNAVAILABLE = 503

############
# DATABASE #
############

DEFAULT_PLAN_ID = 1
FREE_PLAN_ID = 2

MYSQL_TINYINT_MAX_UNSIGNED = 255
MYSQL_SMALLINT_MAX_UNSIGNED = 65535
MYSQL_MEDIUMINT_MAX_UNSIGNED = 16777215
MYSQL_INT_MAX_UNSIGNED = 4294967295
MYSQL_BIGINT_MAX_UNSIGNED = 2**64 - 1

########
# MISC #
########

CONFIG_FILE = 'config.yaml'
DEFAULT_API_KEY_FILE = 'default_api_key.txt'

UUID_VERSION = 4
NULL_UUID = '00000000-0000-0000-0000-000000000000'

ADMIN_ROLE = 'admin'
MAINTAINER_ROLE = 'maintainer'

NUM_RESERVED_CLIENTS = 100

DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S'  # ISO 8601

GENERIC_DOMAINS = {'gmail', 'hotmail', 'outlook'}

INFERENCE_SERVICE_NAME = 'inference_service'
CL_SERVICE_NAME = 'cl_service'  # continual learning
AL_SERVICE_NAME = 'al_service'  # active learning
MONITORING_SERVICE_NAME = 'monitoring_service'
TESTING_SERVICE_NAME = 'testing_service'

DEFAULT_CELERY_BROKER_URL = 'redis://localhost:6379/0'
DEFAULT_CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

THUMBNAIL_SIZE = (128, 128)
